default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: challenge_development

test:
  <<: *default
  database: challenge_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
